clock_pm: export pm_clk symbols needed to build modules that use pm_clk stuff
Recently we have added the pm_clk support in the hcd-stm driver. see
commit f4533c39b214147fdd4f9f088f25c8914deb6a55.

Now a driver (i.e. our hcd-stm) that aims to use pm_clk routines fails when
compiled as module with the error below:

 LD [M]  drivers/usb/core/usbcore.o
  Building modules, stage 2.
  MODPOST 25 modules
ERROR: "pm_clk_add" [drivers/usb/host/hcd-stm.ko] undefined!
ERROR: "pm_clk_init" [drivers/usb/host/hcd-stm.ko] undefined!
ERROR: "pm_clk_destroy" [drivers/usb/host/hcd-stm.ko] undefined!
ERROR: "pm_clk_suspend" [drivers/usb/host/hcd-stm.ko] undefined!
ERROR: "pm_clk_resume" [drivers/usb/host/hcd-stm.ko] undefined!

So this patch adds EXPORT_SYMBOL definitions for the routines
that now are supposed to be used by device drivers.
I guess, this has been never fixed because currently in the main-stream
no driver directly calls these functions.

Signed-off-by: Giuseppe Cavallaro <peppe.cavallaro@st.com>
CC: Francesco Virlinzi <francesco.virlinzi@st.com>