sh:pfc: include sh_pfc.h header file.
This patch includes sh_pfc.h in pfc.c file, without this include kernel
build will throw below errors.

drivers/sh/pfc.c:25:32: warning: ‘struct pinmux_info’ declared inside
parameter list [enabled by default]
drivers/sh/pfc.c:25:32: warning: its scope is only this definition or
declaration, which is probably not what you want [enabled by default]
drivers/sh/pfc.c: In function ‘pfc_iounmap’:
drivers/sh/pfc.c:29:21: error: dereferencing pointer to incomplete type
drivers/sh/pfc.c:30:10:error: dereferencing pointer to incomplete type
drivers/sh/pfc.c:31:15:error: dereferencing pointer to incomplete type
drivers/sh/pfc.c:33:11: error: dereferencing pointer to incomplete type

Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@st.com>